import type { BriefData } from "./types";

const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://shopifyagencydirectory.com";

export async function generatePDF(data: BriefData) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  function checkPage(needed: number) {
    if (y + needed > 270) {
      doc.addPage();
      y = 20;
    }
  }

  function addHeading(text: string) {
    checkPage(16);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(22, 163, 74); // green-600
    doc.text(text, margin, y);
    y += 3;
    doc.setDrawColor(22, 163, 74);
    doc.setLineWidth(0.5);
    doc.line(margin, y, margin + contentWidth, y);
    y += 8;
  }

  function addField(label: string, value: string) {
    if (!value || value === "[]") return;
    checkPage(14);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(107, 114, 128); // gray-500
    doc.text(label.toUpperCase(), margin, y);
    y += 5;
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(17, 24, 39); // gray-900
    const lines = doc.splitTextToSize(value, contentWidth);
    checkPage(lines.length * 5 + 4);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 4;
  }

  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(17, 24, 39);
  doc.text("Shopify Project Brief", margin, y);
  y += 8;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(107, 114, 128);
  const dateStr = new Date().toLocaleDateString(undefined, {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  doc.text(
    `Prepared by ${data.companyName || "Merchant"} \u2022 ${dateStr}`,
    margin,
    y,
  );
  y += 12;

  // Section 1: About Your Business
  addHeading("About Your Business");
  addField("Company Name", data.companyName);
  addField("Website", data.websiteUrl);
  addField("Industry / Niche", data.industry);
  addField("Current Platform", data.currentPlatform);
  addField("Monthly Revenue", data.monthlyRevenue);

  // Section 2: Project Type
  addHeading("Project Type");
  addField("Project", data.projectType);

  // Section 3: Goals & Requirements
  addHeading("Goals & Requirements");
  if (data.goals.length > 0) addField("Primary Goals", data.goals.join(", "));
  addField("Must-Have Features", data.mustHaveFeatures);
  addField("Nice-to-Have Features", data.niceToHaveFeatures);

  // Section 4: Design Preferences
  addHeading("Design Preferences");
  addField("Style Preference", data.designStyle);
  addField("Example Websites", data.exampleWebsites);
  addField("Brand Guidelines Exist?", data.hasBrandGuidelines);

  // Section 5: Technical Requirements
  addHeading("Technical Requirements");
  if (data.integrations.length > 0)
    addField("Integrations Needed", data.integrations.join(", "));
  addField("Product Catalog Size", data.catalogSize);
  addField("Multi-Language Required?", data.multiLanguage);
  addField("Multi-Currency Required?", data.multiCurrency);

  // Section 6: Timeline & Budget
  addHeading("Timeline & Budget");
  addField("Desired Launch Date", data.launchDate);
  addField("Budget Range", data.budgetRange);
  addField("Timeline Flexibility", data.timelineFlexibility);

  // Section 7: Contact Info
  addHeading("Contact Information");
  addField("Name", data.contactName);
  addField("Email", data.contactEmail);
  if (data.contactPhone) addField("Phone", data.contactPhone);
  if (data.additionalNotes) {
    addHeading("Additional Notes");
    addField("Notes", data.additionalNotes);
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(156, 163, 175);
    doc.text(
      `Generated by ${SITE_URL.replace(/^https?:\/\//, "")}/tools/brief-generator`,
      margin,
      287,
    );
    doc.text(`Page ${p} of ${pageCount}`, pageWidth - margin - 20, 287);
  }

  const filename = `shopify-brief-${(data.companyName || "project").toLowerCase().replace(/[^a-z0-9]+/g, "-")}.pdf`;
  doc.save(filename);
}
